# 
# Synthesis run script generated by Vivado
# 

  set_param gui.test TreeTableDev
  set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
set_msg_config -id {Labtools 27-147} -limit 4294967295
create_project -in_memory -part xc7z020clg484-1
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.0 [current_project]
set_param project.compositeFile.enableAutoGeneration 0
set_property default_lib xil_defaultlib [current_project]
read_verilog {
  D:/Code/Trojan/Vivado/AES/AES.srcs/sources_1/imports/AES/bufferin.v
  D:/Code/Trojan/Vivado/AES/AES.srcs/sources_1/imports/AES/bufferout.v
}
set_property file_type "Verilog Header" [get_files D:/Code/Trojan/Vivado/AES/AES.srcs/sources_1/imports/AES/bufferin.v]
set_property file_type "Verilog Header" [get_files D:/Code/Trojan/Vivado/AES/AES.srcs/sources_1/imports/AES/bufferout.v]
read_verilog -library xil_defaultlib {
  D:/Code/Trojan/Vivado/AES/AES.srcs/sources_1/imports/AES/table.v
  D:/Code/Trojan/Vivado/AES/AES.srcs/sources_1/imports/AES/round.v
  D:/Code/Trojan/Vivado/AES/AES.srcs/sources_1/imports/AES/aes_128.v
  D:/Code/Trojan/Vivado/AES/AES.srcs/sources_1/imports/AES/top.v
}
read_xdc D:/Code/Trojan/Vivado/AES/AES.srcs/constrs_1/imports/AES/AES.xdc
set_property used_in_implementation false [get_files D:/Code/Trojan/Vivado/AES/AES.srcs/constrs_1/imports/AES/AES.xdc]

set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir D:/Code/Trojan/Vivado/AES/AES.cache/wt [current_project]
set_property parent.project_dir D:/Code/Trojan/Vivado/AES [current_project]
catch { write_hwdef -file top.hwdef }
synth_design -top top -part xc7z020clg484-1
write_checkpoint top.dcp
report_utilization -file top_utilization_synth.rpt -pb top_utilization_synth.pb
